### ISSUE TITLE
exec: "/bin/echo": stat /bin/echo: no such file or directory

### ISSUE THREAD

**Issue by Jamlee** [kasperisager/phpstack#15] opened 2015-03-27 09:07 UTC
when I stop all container and restart all,I occur that "exec: "/bin/echo": stat /bin/echo: no such file or directory"

**Comment by bedeoverend** [comment] 2015-04-15 02:45
Yup I get the same issue unfortunately

**Comment by kasperisager** [comment] 2015-04-15 07:18
I'm investigating.

**Comment by kasperisager** [comment] 2015-04-15 08:57
Feck, a998e14 didn't survive a restart.

**Comment by kasperisager** [comment] 2015-04-15 08:59
The issue is related to docker/compose#919.

**Comment by bedeoverend** [comment] 2015-04-16 02:59
Damn. So no fix on the horizon?

**Comment by kasperisager** [comment] 2015-04-16 07:05
I'm afraid not. A workaround is to do `docker-compose rm shipyard` prior to every `up` or simply commenting out the Shipyard container in `docker-compose.yml`.

**Comment by kasperisager** [comment] 2015-05-07 14:58
Looks like a fix is scheduled for Compose 1.3.0: docker/compose#1349

**Comment by kasperisager** [comment] 2015-05-08 09:39
The above mentioned fix has been merged so hopefully this issue will resolve itself by the time Compose 1.3.0 hits the deck.

**Comment by dydx** [comment] 2015-06-05 06:55
I'm experiencing this tonight. I'm trying out just dropping the `shipyard` stuff from `docker-compose.yml` as a quick workaround :8ball:

**Comment by matheusmmo** [comment] 2015-09-05 01:40
For me, updating to docker-compose 1.4.0 solved the problem. Anyone else?

**Comment by kasperisager** [comment] 2015-09-05 09:51
Compose 1.4 has been out for a while so I'll close this.

**Closed by kasperisager** 2015-09-05 09:51 UTC
Labels: bug
